export const EDITOR_SET_COMPILED = 'EDITOR_SET_COMPILED'
export const EDITOR_SET_ERROR = 'EDITOR_SET_ERROR'
export const EDITOR_SET_CODE = 'EDITOR_SET_CODE'
export const EDITOR_SET_THEME = 'EDITOR_SET_THEME'
export const EDITOR_NAV_TO = 'EDITOR_NAV_TO'
export const EDITOR_TOGGLE_PROCESSED = 'EDITOR_TOGGLE_PROCESSED'
export const EDITOR_SET_LANG = 'EDITOR_SET_LANG'

export const SET_THEME_TRANSITION = 'SET_THEME_TRANSITION'
