// Editor
export const EDITOR_SET_COMPILED = 'EDITOR_SET_COMPILED'
export const EDITOR_SET_ERROR = 'EDITOR_SET_ERROR'
export const EDITOR_SET_CODE = 'EDITOR_SET_CODE'
export const EDITOR_SET_THEME = 'EDITOR_SET_THEME'
export const EDITOR_NAV_TO = 'EDITOR_NAV_TO'
export const EDITOR_TOGGLE_COMPILED = 'EDITOR_TOGGLE_COMPILED'
export const EDITOR_SET_LANG = 'EDITOR_SET_LANG'
export const EDITOR_SET_LAYOUT = 'EDITOR_SET_LAYOUT'
export const EDITOR_PUT_OPTIONS = 'EDITOR_PUT_OPTIONS'

// UI
export const SET_THEME_TRANSITION = 'SET_THEME_TRANSITION'

// Sheet
export const SHEET_SET_TXHASH = 'SHEET_SET_TXHASH'
export const SHEET_SET_SAVING = 'SHEET_SET_SAVING'
export const SHEET_SET_HASHES = 'SHEET_SET_HASHES'
