// Editor
export const EDITOR_SET_COMPILED = 'EDITOR_SET_COMPILED'
export const EDITOR_SET_ERROR = 'EDITOR_SET_ERROR'
export const EDITOR_SET_CODE = 'EDITOR_SET_CODE'
export const EDITOR_NAV_TO = 'EDITOR_NAV_TO'
export const EDITOR_TOGGLE_COMPILED = 'EDITOR_TOGGLE_COMPILED'
export const EDITOR_SET_LANG = 'EDITOR_SET_LANG'
export const EDITOR_SET_LAYOUT = 'EDITOR_SET_LAYOUT'
export const EDITOR_PUT_OPTIONS = 'EDITOR_PUT_OPTIONS'
export const EDITOR_SET_LIBS = 'EDITOR_SET_LIBS'
export const EDITOR_SET_IFRAME = 'EDITOR_SET_IFRAME'
export const EDITOR_LOAD_SETTINGS = 'EDITOR_LOAD_SETTINGS'

// UI
export const SET_THEME_TRANSITION = 'SET_THEME_TRANSITION'
export const SET_THEME = 'SET_THEME'

// Sheet
export const SHEET_SET_TXHASH = 'SHEET_SET_TXHASH'
export const SHEET_SET_SAVING = 'SHEET_SET_SAVING'
export const SHEET_SET_IPFS_HASHES = 'SHEET_SET_IPFS_HASHES'
export const SHEET_SET_HASH = 'SHEET_SET_HASH'

// Profile
export const SET_USER_PROFILE = 'SET_USER_PROFILE'
export const SET_SHEET_LIST = 'SET_SHEET_LIST'

// Homepage
export const HOME_SET_SHEETS = 'HOME_SET_SHEETS'
export const SET_LOGGED_USER = 'SET_LOGGED_USER'
